Lights group Implemented
luxteam/jobs_test_web_viewer pull request #110
Opened 2023-02-02 06:54 UTC by Sofshik

https://rpr.cis.luxoft.com/job/RenderStudio-Manual/965/

2023-02-02 07:48 UTC, Sofshik commented
Viewport 11th case: https://rpr.cis.luxoft.com/job/RenderStudio-Manual/970/

2023-02-02 13:29 UTC, Speedwag00n requested changes

2023-02-02 13:58 UTC, Sofshik commented on jobs/Scripts/extensions/Viewport.py
> +    actions.move_to_element(element).perform()
Сначала прокручивается вкладка scene index, чтобы было видно кнопку удаления объекта, затем курсор наводится на строку с холодильником, а потом удаляем холодильник. Пыталась сделать проще, но с кнопкой не получается взаимодействовать, если она не в поле зрения, а решения для горизонтального скроллинга из селениума работать не стали.

2023-02-02 13:58 UTC, Sofshik commented on jobs/Scripts/steps.py
> +        actions.move_to_element(element).perform()
Добавлю

2023-02-03 15:35 UTC, Speedwag00n approved these changes
Сейчас выглядит хорошо, отправлю еще QA на ревью

2023-02-13 08:34 UTC, Speedwag00n requested changes
Вроде бы как пропущен этот момент из документа с правками
34, 35 - Exposure is set to 0, can’t see light change

2023-02-14 15:33 UTC, merged