Application reusage
luxteam/jobs_test_web_viewer pull request #117
Opened 2023-02-04 07:14 UTC by Sofshik

https://rpr.cis.luxoft.com/job/RenderStudio-Manual/981/

2023-02-06 09:49 UTC, Speedwag00n requested changes

2023-02-06 09:49 UTC, Speedwag00n commented on jobs/Tests/Viewport/test_cases-desktop.json
> +        "leave_open": true
"Measure scene loading time", при этом в репорте Scene loading time: 0.0

2023-02-06 09:49 UTC, Speedwag00n commented on jobs/Scripts/extensions/Viewport.py
>      CommonSteps.click_tab(driver, 'scene index', 'close')
Не учтен такой момент: запускается этот кейс в первый раз, студия по каким-то причинам крашится, закрываем его. Делаем ретрай, открываем студию снова, а нужная вкладка не открыта

2023-02-06 09:49 UTC, Speedwag00n commented on jobs/Scripts/extensions/Viewport.py
>      CommonSteps.click_tab(driver, 'timeline', 'close')
Не учтен такой момент: запускается этот кейс в первый раз, студия по каким-то причинам крашится, закрываем его. Делаем ретрай, открываем студию снова, а нужная вкладка не открыта

2023-02-06 09:49 UTC, Speedwag00n commented on jobs/Scripts/extensions/Viewport.py
>      CommonSteps.click_tab(driver, 'comments', 'close')
Не учтен такой момент: запускается этот кейс в первый раз, студия по каким-то причинам крашится, закрываем его. Делаем ретрай, открываем студию снова, а нужная вкладка не открыта

2023-02-06 09:49 UTC, Speedwag00n commented on jobs/Scripts/extensions/Viewport.py
>      CommonSteps.click_tab(driver, 'menu', 'close')
Не учтен такой момент: запускается этот кейс в первый раз, студия по каким-то причинам крашится, закрываем его. Делаем ретрай, открываем студию снова, а нужная вкладка не открыта

2023-02-06 09:49 UTC, Speedwag00n commented on jobs/Tests/Library/test_cases-desktop.json
> +        "leave_open": true
Не учтен такой момент: запускается этот кейс в первый раз, студия по каким-то причинам крашится, закрываем его. Делаем ретрай, открываем студию снова, а нужная вкладка не открыта

2023-02-06 09:49 UTC, Speedwag00n commented on jobs/Scripts/extensions/Complex_Scenes.py
> -    rotate_scene(driver)
Не учтен такой момент: запускается этот кейс в первый раз, студия по каким-то причинам крашится, закрываем его. Делаем ретрай, открываем студию снова, но нужного поворота там не будет

2023-02-06 09:49 UTC, Speedwag00n commented on jobs/Scripts/extensions/Complex_Scenes.py
> -    rotate_scene(driver)
Не учтен такой момент: запускается этот кейс в первый раз, студия по каким-то причинам крашится, закрываем его. Делаем ретрай, открываем студию снова, но нужного поворота там не будет

2023-02-06 09:49 UTC, Speedwag00n commented on jobs/Scripts/extensions/Animation.py
>      sleep(0.3)
Это не относится к этому ПРу, но можно тут пофиксить заодно
Нужно эту задержку сделать чуть больше (на 0.3-0.5) + то же самое в похожих кейсах этой же группы

2023-02-09 06:31 UTC, Sofshik commented
https://rpr.cis.luxoft.com/job/RenderStudio-Manual/989/

2023-02-10 10:55 UTC, Speedwag00n commented on jobs/Tests/Viewport/test_cases-desktop.json
> +        "leave_open": true
Сейчас тоже 0.0, нужно поправить

2023-02-10 11:00 UTC, Speedwag00n commented
В FinalRender 7 и 8 сцена не поворачивается
А так выглядит хорошо. Нужно будет в начале следующей недели вмерджить все изменения из мастера и полностью прогнать на всех имеющихся сейчас картах, т.к. местами нужно будет обновить бейзлайны + пусть это посмотрят QA

2023-02-10 11:00 UTC, Speedwag00n requested changes
В FinalRender 7 и 8 сцена не поворачивается
А так выглядит хорошо. Нужно будет в начале следующей недели вмерджить все изменения из мастера и полностью прогнать на всех имеющихся сейчас картах, т.к. местами нужно будет обновить бейзлайны + пусть это посмотрят QA

2023-02-11 07:07 UTC, Sofshik commented
> В FinalRender 7 и 8 сцена не поворачивается А так выглядит хорошо. Нужно будет в начале следующей недели вмерджить все изменения из мастера и полностью прогнать на всех имеющихся сейчас картах, т.к. местами нужно будет обновить бейзлайны + пусть это посмотрят QA

https://github.com/luxteam/jobs_test_web_viewer/blob/e280131148da3c8e6faf955a8bf78d93001eb79d/jobs/Scripts/steps.py#L107-L113
В каком-то из коммитов был добавлен поворот обратно. Так что он тут происходит, просто сцена возвращаенся к первоначальному виду

2023-02-19 12:37 UTC, merged