Setting status and script_info by platform
luxteam/jobs_test_web_viewer pull request #148
Opened 2023-03-22 14:41 UTC by Sofshik

https://rpr.cis.luxoft.com/job/RenderStudio-Manual/1142/

2023-03-22 15:07 UTC, Speedwag00n requested changes

2023-03-22 15:07 UTC, Speedwag00n commented on jobs/Scripts/simpleRender.py
> +                case["script_info"] += new_info
Предлагаю сделать так, чтобы get_info_by_platform возвращал уже готовый вариант script_info (script_info + строки из script_info_by_platform, если есть совпадение, или только script_info, если совпадений нет)
Тогда можно было бы эту логику сократить до
case["script_info"] = get_info_by_platform(case)

И давай тогда функцию get_info_by_platform переименуем простов get_script_info

2023-03-24 12:15 UTC, Sofshik commented
https://rpr.cis.luxoft.com/job/RenderStudio-Manual/1154/

2023-03-24 18:20 UTC, Sofshik commented
https://rpr.cis.luxoft.com/job/RenderStudio-Manual/1155/

2023-03-24 18:30 UTC, Speedwag00n approved these changes

2023-04-06 12:33 UTC, Sofshik commented
Extend script_info_by_platform key: https://rpr.cis.luxoft.com/job/RenderStudio-Manual/1187/

2023-04-07 06:54 UTC, Speedwag00n approved these changes

2023-04-07 06:55 UTC, merged