Properties actualization
luxteam/jobs_test_web_viewer pull request #175
Opened 2023-05-10 22:08 UTC by Sofshik

2023-05-11 06:57 UTC, Speedwag00n requested changes

2023-05-11 06:57 UTC, Speedwag00n commented on jobs/Scripts/extensions/Properties.py
> +    LibrarySteps.select_element(driver, "Sphere_Light")
Почему в этой функции вызывается LibrarySteps.select_element для поиска Sphere_Light, а в функции для 4-ого кейса - ViewportSteps.search_scene_element?

2023-05-11 06:57 UTC, Speedwag00n commented on jobs/Scripts/extensions/Properties.py
> +    LibrarySteps.select_element(driver, "Cone")
Группа Cone не выбирается, судя по скриншоту

2023-05-11 06:57 UTC, Speedwag00n commented on jobs/Scripts/extensions/Properties.py
> +def test_007(args, case, driver, current_try):
В этом кейсы отсутствует выставление Intensity + Exposure и порядок действий отличается от описания (вы описании сперва применяются настройки, после открываются вкладки transform и light settings, здесь наоборот)

2023-05-11 06:57 UTC, Speedwag00n commented on jobs/Scripts/extensions/Properties.py
> +    PropertiesSteps.set(driver, "location", "y", "5")
```suggestion
    PropertiesSteps.set(driver, "location", "y", "-5")
```

2023-05-11 10:28 UTC, Sofshik commented on jobs/Scripts/extensions/Properties.py
> +    LibrarySteps.select_element(driver, "Sphere_Light")
В 4-ом кейсе это делается для удаления объекта: так как кнопка удаления отображения только при наведении, сначала мы ищем нужный объект, но не кликаем на него (поэтому там ViewportSteps.search_scene_element, а не LibrarySteps.select_element)

2023-05-16 09:41 UTC, Speedwag00n approved these changes

2023-05-16 09:41 UTC, merged