Fix materials cases
luxteam/jobs_test_web_viewer pull request #58
Opened 2022-11-14 11:40 UTC by Sofshik

https://cis.nas.stvcis.com:5443/RenderStudio-Manual/800/Test_Report/test_report.html

2022-11-15 07:10 UTC, Speedwag00n requested changes

2022-11-15 07:10 UTC, Speedwag00n commented on jobs/Scripts/locators.py
> +    MATERIAL_CARD = '//div[ @id="row-0" ]//div[ contains(@class, "materials-table-content") ]//h2'
На будущее: изменение для разных тикетов должны быть в разных ветках. Это изменения для тикета с актуализацией кейса на сортировку

2022-11-15 07:10 UTC, Speedwag00n commented on jobs/Scripts/utils.py
> +    material_cards = find_by_xpath(LibraryLocators.MATERIAL_CARDS, driver, True)
Эту логику нужно сделать более универсальной
Пытаемся найти материал. Если его не удается найти, прокручиваем меню. Прокрутку меню необходимо сделать через selenium без использования кликов по координатам

2022-11-15 12:57 UTC, Sofshik commented
https://cis.nas.stvcis.com:5443/RenderStudio-Manual/802/Test_Report/test_report.html

2022-11-15 14:49 UTC, Speedwag00n requested changes

2022-11-15 14:49 UTC, Speedwag00n commented on jobs/Scripts/utils.py
>      if material_name == "Marble Tiles" or material_name == "TH: Brick Wall":
Хотелось бы избавиться от этой проверки, чтобы не привязываться к определенным материалам прямо в функции
Как вариант, добавить новое булево поле в JSON. Если оно true - прокручиваем страницу, если нет, то сразу ищем материал

2022-11-17 17:32 UTC, Speedwag00n commented on jobs/Scripts/extensions/Materials.py
> +    LibrarySteps.test_material(driver, case["material_name"], case["scroll"])
Лучше сделать scroll опциональным полем кейса. Например, если оно не указано, считаем, что оно равно false

2022-11-17 17:34 UTC, Speedwag00n commented on jobs/Scripts/utils.py
> +def choose_material(material_name, driver, scroll, click = True):
Эта функция также используется в группах Scenes и Library. Если там не обновить параметры, они сломаются. Еще один попод добавить значение по-умолчанию

https://github.com/luxteam/jobs_test_web_viewer/blob/77cd0c4762151f28a940876ac9dcf49c13074da0/jobs/Scripts/extensions/Scenes.py#L69
https://github.com/luxteam/jobs_test_web_viewer/blob/73db93cb1b5ee452fda86f69fabb1ed681f66ded/jobs/Scripts/extensions/Library.py#L40

2022-11-17 17:35 UTC, Speedwag00n requested changes
Нужно доработать использование нового поля

2022-11-18 09:40 UTC, Speedwag00n requested changes
Этот момент все еще нужно доработать
https://github.com/luxteam/jobs_test_web_viewer/pull/58/files#r1025491844

2022-11-19 15:31 UTC, Sofshik commented
https://cis.nas.stvcis.com:5443/RenderStudio-Manual/829/Test_Report_Desktop/test_report.html

Проверила также на Library и Scenes группах, с параметром scroll работает
https://cis.nas.stvcis.com:5443/RenderStudio-Manual/831/Test_Report_Desktop/test_report.html

2022-11-21 17:26 UTC, Speedwag00n approved these changes

2022-11-21 17:26 UTC, merged