Auto installation of chromedriver
luxteam/jobs_test_web_viewer pull request #63
Opened 2022-11-18 09:28 UTC by Sofshik

https://cis.nas.stvcis.com:5443/RenderStudio-Manual/830/Test_Report_Desktop/test_report.html

2022-11-18 10:14 UTC, Speedwag00n requested changes

2022-11-18 10:14 UTC, Speedwag00n commented on jobs/Scripts/utils.py
> +        os.remove('..\\driver\\chromedriver.exe')
Эту логику можно немного оптимизировать
В процессе работы автотестов часто будут ситуации, когда будет использоваться один и тот же драйвер по многу раз подряд. Скачивать его каждый раз заново не очень целесообразно
Можно рядом с драйвером сохранять JSON с информацией о версии хрома, для которого этот драйвер был скачан
Ее можно будет проверять и не скачивать драйвер, когда нужный драйвер уже скачан

2022-11-29 09:54 UTC, Sofshik commented
https://rpr.cis.luxoft.com/job/RenderStudio-Manual/851/
Работает и на десктоп-версии, и на веб-версии нормально.

2022-11-29 12:38 UTC, Speedwag00n approved these changes
Ждем билд. Если все хорошо, то мержим

2022-11-29 16:17 UTC, merged