Animation group implemented
luxteam/jobs_test_web_viewer pull request #99
Opened 2023-01-04 12:49 UTC by Sofshik

https://rpr.cis.luxoft.com/job/RenderStudio-Manual/919/

2023-01-04 14:56 UTC, Speedwag00n requested changes

2023-01-04 14:56 UTC, Speedwag00n commented on jobs/Scripts/extensions/Animation.py
> +    sleep(8)
Нужно добавить проверку, что текущий фрейм не равен 0

2023-01-04 14:56 UTC, Speedwag00n commented on jobs/Scripts/extensions/Animation.py
> +    sleep(8)
Нужно добавить проверку, что текущий фрейм равен 0

2023-01-04 14:56 UTC, Speedwag00n commented on jobs/Scripts/extensions/Animation.py
> +    sleep(8)
Нужно добавить проверку, что текущий фрейм равен 2048

2023-01-04 14:56 UTC, Speedwag00n commented on jobs/Scripts/steps.py
> +    def click_timeline_button(driver, button, sec):
sec лучше переименовать в delay и сделать опциональным параметром

2023-01-04 14:56 UTC, Speedwag00n commented on jobs/Scripts/extensions/Animation.py
> +    sleep(8)
Нужно добавить проверку, что значение в поле frame равно 10

2023-01-04 14:56 UTC, Speedwag00n commented on jobs/Scripts/extensions/Animation.py
> +    sleep(8)
Нужно добавить проверку, что значение в поле start равно 10

2023-01-04 14:56 UTC, Speedwag00n commented on jobs/Scripts/extensions/Animation.py
> +    sleep(8)
Нужно добавить проверку, что значение в поле end равно 10

2023-01-04 14:56 UTC, Speedwag00n commented on jobs/Scripts/extensions/Animation.py
> +    sleep(8)
Нужно добавить проверку, что значение в поле frame равно 1

2023-01-04 14:56 UTC, Speedwag00n commented on jobs/Scripts/extensions/Animation.py
> +    sleep(8)
Нужно добавить проверку, что значение в поле frame равно 9

2023-01-04 14:56 UTC, Speedwag00n commented on jobs/Scripts/extensions/Animation.py
> +    sleep(8)
Нужно добавить проверку, что значение в поле end равно 11

2023-01-04 14:56 UTC, Speedwag00n commented on jobs/Scripts/extensions/Animation.py
> +    sleep(8)
Нужно добавить проверку, что значение в поле end равно 9

2023-01-09 18:26 UTC, Sofshik commented
Исправлено
https://rpr.cis.luxoft.com/job/RenderStudio-Manual/921/

2023-01-11 07:22 UTC, Speedwag00n approved these changes

2023-01-11 07:22 UTC, merged